language: node_js
node_js:
  - 12

cache:
  directories:
    - backend/node_modules

branches:
  only:
  - master
  - stage

install:
    - cd backend
    - npm install
    - npm install -g serverless

stages:
  - name: pull_request
    if: type = pull_request AND branch IN (master, stage)
  - name: stage
    if: type = push AND branch = stage
  - name: prod
    if: type = push AND branch = master

jobs:
  include:
    - stage: pull_request
      script:
        - echo 'Test Pull Request!!'
        - sls package -v --stage dev
        # TODO Build web-client, run tests
    - stage: stage
      script:
        - echo 'Test Push stage!!'
        - sls deploy -v --stage dev
        # TODO Build web-client, run tests, deploy to dev
    - stage: prod
      script:
        - echo 'Build and deploy for Production'
        - sls deploy -v --stage prod
        # TODO Build and deploy web-client