language: node_js
node_js:
  - 12

cache:
  directories:
    - backend/node_modules

install:
  - cd backend
  - npm ci
  - npm install -g serverless
  - cd ../web-client
  - npm install -g serverless
  - npm ci

stages:
  - name: pull_request
    if: type = pull_request AND branch IN (master, stage)
  - name: stage
    if: type = push AND branch = stage
  - name: prod
    if: type = push AND branch = master

jobs:
  include:
    - stage: pull_request
      script:
        - echo 'Test Pull Request!!'
        - cd ../backend
        - npm test
        - sls package -v --stage dev
        - cd ../web-client
        - CI=false npm run build
    - stage: stage
      script:
        - echo 'Test, build and deploy to dev'
        - cd ../backend
        - npm test
        - sls deploy -v --stage dev
        - cd ../web-client
        - CI=false npm run build
        - sls client deploy --no-confirm --stage dev
    - stage: prod
      script:
        - echo 'Test, build and deploy to prod'
        - cd ../backend
        - npm test
        - sls deploy -v --stage prod
        - cd ../web-client
        - CI=false npm run build
        - sls client deploy --no-confirm --stage prod
