language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

branches:
  only:
  - master
  - stage

install:
    - cd backend
    - npm install
    - npm install -g serverless

stages:
    # require the type to be a PR
  - name: test
    if: type = pull_request
    # require the type to be push to master
  - name: deploy
    if: type = push AND branch = master

jobs:
  include:
    - stage: test
      script:
        - echo 'Test Deploy!!'
        - sls package -v --stage dev

    - stage: deploy
      script:
        - echo 'Test Deploy!!'
        - sls deploy -v --stage dev
