language: node_js
node_js:
  - 12
cache:
  directories:
    - backend/node_modules
script:
    - cd backend
    - npm install -g serverless serverless-webpack serverless-iam-roles-per-function
    - sls deploy -v
