service:
  name: grifor-serverless-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}

  tracing:
    lambda: true
    apiGateway: true

  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    SCHEDULE_TABLE: WorkScheduleTable-${self:provider.stage}
    REGION: ${opt:region}
    USER_POOL_ID: ${self:provider.region}_sJRdbCIjo

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
        - "@types/aws-lambda"

  serverless-offline:
    httpPort: 4000

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  - ${file(resources/schedule-functions.yml)}
  - ${file(resources/users-functions.yml)}

resources:
  # API Gateway
  - ${file(resources/api-gateway.yml)}
  # Cognito
  - ${file(resources/cognito.yml)}
  # DynamoDB
  - ${file(resources/dynamodb.yml)}
