Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:service.name}-${self:provider.stage}-user-pool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UsernameConfiguration:
        CaseSensitive: true
      Schema:
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: true
        - Name: address
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: role
          AttributeDataType: String
          Mutable: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:service.name}-${self:provider.stage}-user-pool-client
      AllowedOAuthFlows: ["code"]
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes: ["openid", "profile", "aws.cognito.signin.user.admin"]
      CallbackURLs: ["https://ek-capstone-app.s3.us-east-2.amazonaws.com/callback"]
      DefaultRedirectURI: "https://ek-capstone-app.s3.us-east-2.amazonaws.com/callback"
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: true
      UserPoolId:
        Ref: CognitoUserPool

  # CognitoUserPoolDomain:
  #   Type: AWS::Cognito::UserPoolDomain
  #   Properties:
  #     Domain: MYDOMAIN # what is before .auth.REGION.amazoncognito.com
  #     UserPoolId:
  #       Ref: CognitoUserPool # given the name of your resource

  MyApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 10
      IdentitySource: method.request.header.Authorization
      Name: MyCognitoAuthorizer
      RestApiId:
        Ref: ApiGatewayRestApi
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - {"Fn::Join": ["", ["arn:aws:cognito-idp:", {Ref: "AWS::Region"}, ":", {Ref: "AWS::AccountId"}, ":userpool/", Ref: CognitoUserPool]]}

# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient

# CognitoUserPoolClient:
#      Type: AWS::Cognito::UserPoolClient
#      Properties:
#        ClientName: ${self:custom.name}-client
#        SupportedIdentityProviders: ["COGNITO"]
#        AllowedOAuthFlowsUserPoolClient: true
#        AllowedOAuthFlows: ["code"]
#        CallbackURLs: ["http://localhost:3000/callback"]
#        DefaultRedirectURI: "http://localhost:3000/callback"
#        AllowedOAuthScopes: ["email", "openid", "profile", "aws.cognito.signin.user.admin"]
#        GenerateSecret: false
#        UserPoolId:
#          Ref: CognitoUserPool