Resources:
  WorkScheduleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: year
          AttributeType: N
        - AttributeName: month
          AttributeType: N
      KeySchema:
        - AttributeName: year
          KeyType: HASH
        - AttributeName: month
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.SCHEDULE_TABLE}


# Print out the Id of the User Pool that is created
Outputs:
  DynamoDbTable:
    Value:
      Ref: WorkScheduleTable